print("Getting to Know you!")
NAME = input("What is your name? ")
FOOD = input("What is your favorite food? ")
MUSIC = input("What is your favorite music? ")
LIVE = input("Where do you live? ")
print()
print("You are: " + NAME)
print("You are probably hungry for: " + FOOD)
print("And you are definetly getting your groove on to: " + MUSIC)
print("living in the amazing: " + LIVE)